/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import DModules.DMObras;
import DModules.DMServicios;
import MapeoTablas.DBObras;
import MapeoTablas.DBServicios;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author estef
 */
public class FMenuServicios extends javax.swing.JFrame {

    private final DMServicios dmServicios;
    private final DMObras dmObras;

    private ArrayList<DBServicios> listaServicios;
    private ArrayList<DBObras> listaObras;

    private DBServicios servicioSeleccionado = null;
    private MaskFormatter mascaraFecha;

    /**
     * Creates new form FServicios
     */
    public FMenuServicios() {
        this.dmServicios = new DMServicios();
        this.dmObras = new DMObras();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServicios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlTrabajador = new javax.swing.JLabel();
        jcbObras = new javax.swing.JComboBox<>();
        jlErrorHoraFin = new javax.swing.JLabel();
        jbInsertar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jFormattedTextFieldDFecha = new javax.swing.JFormattedTextField();
        jSpinnerHoraIni = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerMinInicio = new javax.swing.JSpinner();
        jSpinnerHoraFin = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerMinFin = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Obra", "Fecha", "Hora Inicio", "Hora Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableServiciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableServicios);

        jLabel1.setText("Trabajador:");

        jLabel2.setText("Obra : ");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Hora inicio:");

        jLabel5.setText("Hora fin:");

        jcbObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbObrasActionPerformed(evt);
            }
        });

        jlErrorHoraFin.setText("jLabel9");

        jbInsertar.setText("Insertar");
        jbInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInsertarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jFormattedTextFieldDFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDFechaActionPerformed(evt);
            }
        });

        jSpinnerHoraIni.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabel6.setText(":");

        jSpinnerMinInicio.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jSpinnerHoraFin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabel7.setText(":");

        jSpinnerMinFin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldDFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSpinnerHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(jSpinnerMinInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinnerHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinnerMinFin, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)))
                                .addGap(86, 86, 86)
                                .addComponent(jlErrorHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(jLabel7)
                    .addContainerGap(444, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldDFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinnerMinInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlErrorHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMinFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInsertar)
                    .addComponent(jbModificar)
                    .addComponent(jbEliminar)
                    .addComponent(jbCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(289, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            mascaraFecha = new MaskFormatter("####/##/##");
            mascaraFecha.setPlaceholderCharacter('_');
            mascaraFecha.setValidCharacters("0123456789");
            mascaraFecha.install(jFormattedTextFieldDFecha);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al configurar la máscara de fecha.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

        }
        jlTrabajador.setText(FMenuPrincipal.usuario.getDescripcion());
        cargarObras();
        cargarTabla();

        jbModificar.setEnabled(false);
        jbEliminar.setEnabled(false);
        jbCancelar.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void limpiarCampos() {
        jFormattedTextFieldDFecha.setText("");
        jSpinnerHoraIni.setValue(0);
        jSpinnerMinInicio.setValue(0);
        jSpinnerHoraFin.setValue(0);
        jSpinnerMinFin.setValue(0);
        jTableServicios.clearSelection();
        servicioSeleccionado = null;

        jcbObras.setEnabled(true);
        jFormattedTextFieldDFecha.setEnabled(true);
        jSpinnerHoraIni.setEnabled(true);
        jSpinnerMinInicio.setEnabled(true);
    }

    private void jFormattedTextFieldDFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDFechaActionPerformed

    private void jcbObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbObrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbObrasActionPerformed

    private void jTableServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableServiciosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            
            int filaSeleccionada = jTableServicios.getSelectedRow();
            
            // Solo procesamos si hay una fila válida seleccionada
            if (filaSeleccionada >= 0 && listaServicios != null && filaSeleccionada < listaServicios.size()) {
                
                jbInsertar.setEnabled(false);
                jbModificar.setEnabled(true);
                jbEliminar.setEnabled(true);
                jbCancelar.setEnabled(true);

                setCamposFromTable();
                
            } else {
                 // Si se hace doble clic en un área vacía o si la lista está vacía.
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_jTableServiciosMouseClicked

    private String obtenerCodObraSeleccionada() {
        int selectedIndex = jcbObras.getSelectedIndex();
        if (selectedIndex != -1 && selectedIndex < listaObras.size()) {
            return listaObras.get(selectedIndex).getCodObra();
        }
        return null;
    }

    private int horaAIntMinutos(String horaStr) {
        try {
            int h = Integer.parseInt(horaStr.substring(0, 2));
            int m = Integer.parseInt(horaStr.substring(2, 4));
            return h * 60 + m;
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    private boolean existeSuperposicionHoraria(String nifTrab, String fecha, String horaInicio, String horaFin) {

        int nuevoInicio = horaAIntMinutos(horaInicio);
        int nuevoFin = horaAIntMinutos(horaFin);

        for (DBServicios existente : listaServicios) {

            if (existente.getNifTrab().equals(nifTrab) && existente.getFecha().equals(fecha)) {

                int existenteInicio = horaAIntMinutos(existente.getHoraInicio());
                int existenteFin = horaAIntMinutos(existente.getHoraFin());

                if (nuevoInicio < existenteFin && nuevoFin > existenteInicio) {
                    return true;
                }
            }
        }
        return false;
    }

    private void jbInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInsertarActionPerformed
        // TODO add your handling code here:
        String nifTrab = FMenuPrincipal.usuario.getNif();
        String codObra = obtenerCodObraSeleccionada();
        String fechaGUI = jFormattedTextFieldDFecha.getText().replace("/", "").trim();

        if (codObra == null || fechaGUI.contains("_") || fechaGUI.length() != 8) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar la obra y completar la fecha (YYYY/MM/DD).", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String hIni = String.format("%02d", (Integer) jSpinnerHoraIni.getValue());
        String mIni = String.format("%02d", (Integer) jSpinnerMinInicio.getValue());
        String hFin = String.format("%02d", (Integer) jSpinnerHoraFin.getValue());
        String mFin = String.format("%02d", (Integer) jSpinnerMinFin.getValue());

        String horaInicio = hIni + mIni;
        String horaFin = hFin + mFin;

        int minTotalIni = (Integer) jSpinnerHoraIni.getValue() * 60 + (Integer) jSpinnerMinInicio.getValue();
        int minTotalFin = (Integer) jSpinnerHoraFin.getValue() * 60 + (Integer) jSpinnerMinFin.getValue();

        if (!validarHora(minTotalIni, minTotalFin)) {
            return;
        }

        if (existeSuperposicionHoraria(nifTrab, fechaGUI, horaInicio, horaFin)) {
            JOptionPane.showMessageDialog(
                    this,
                    "El horario seleccionado se solapa con un servicio ya existente en esta fecha.",
                    "Error de Horario",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        DBServicios nuevoServicio = new DBServicios(nifTrab, codObra, fechaGUI, horaInicio, horaFin);

        try {
            if (dmServicios.insertar(nuevoServicio)) {
                JOptionPane.showMessageDialog(this, "Servicio insertado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo insertar. Ya existe un servicio con esa clave primaria.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al insertar en la BD: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbInsertarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        jbInsertar.setEnabled(true);
        jbModificar.setEnabled(false);
        jbEliminar.setEnabled(false);
        jbCancelar.setEnabled(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        if (servicioSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un servicio de la tabla para modificar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String hFin = String.format("%02d", (Integer) jSpinnerHoraFin.getValue());
        String mFin = String.format("%02d", (Integer) jSpinnerMinFin.getValue());
        String nuevaHoraFin = hFin + mFin;

        int hIniActual = Integer.parseInt(servicioSeleccionado.getHoraInicio().substring(0, 2));
        int mIniActual = Integer.parseInt(servicioSeleccionado.getHoraInicio().substring(2, 4));
        int minTotalIni = hIniActual * 60 + mIniActual;
        int minTotalFin = (Integer) jSpinnerHoraFin.getValue() * 60 + (Integer) jSpinnerMinFin.getValue();

        if (!validarHora(minTotalIni, minTotalFin)) {
            return;
        }

        DBServicios claveAntigua = new DBServicios(
                servicioSeleccionado.getNifTrab(),
                servicioSeleccionado.getCodObra(),
                servicioSeleccionado.getFecha(),
                servicioSeleccionado.getHoraInicio(),
                servicioSeleccionado.getHoraFin()
        );

        DBServicios servicioNuevo = new DBServicios(
                servicioSeleccionado.getNifTrab(),
                servicioSeleccionado.getCodObra(),
                servicioSeleccionado.getFecha(),
                servicioSeleccionado.getHoraInicio(),
                nuevaHoraFin
        );

        try {
            if (dmServicios.modificar(servicioNuevo, claveAntigua)) {
                JOptionPane.showMessageDialog(this, "Servicio modificado (Hora Fin) correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarTabla();
                jbCancelarActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo modificar el servicio. La clave primaria no pudo ser encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al modificar en la BD: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        if (servicioSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un servicio de la tabla para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro que desea eliminar el servicio seleccionado para la obra " + servicioSeleccionado.getCodObra() + " a las " + servicioSeleccionado.getHoraInicio() + "?", 
                "Confirmar Eliminación", 
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (dmServicios.eliminar(servicioSeleccionado)) {
                    JOptionPane.showMessageDialog(this, "Servicio eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    cargarTabla();
                    jbCancelarActionPerformed(null); 
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el servicio.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar en la BD: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void setCamposFromTable() {
        int filaSeleccionada = jTableServicios.getSelectedRow();

        if (filaSeleccionada >= 0 && listaServicios != null && filaSeleccionada < listaServicios.size()) {
            
            servicioSeleccionado = listaServicios.get(filaSeleccionada); 

            String codObra = servicioSeleccionado.getCodObra();
            for (int i = 0; i < listaObras.size(); i++) {
                if (listaObras.get(i).getCodObra().equals(codObra)) {
                    jcbObras.setSelectedIndex(i);
                    break;
                }
            }

            jcbObras.setEnabled(false);
            jFormattedTextFieldDFecha.setEnabled(false);
            jSpinnerHoraIni.setEnabled(false);
            jSpinnerMinInicio.setEnabled(false);
            
            String fechaBD = servicioSeleccionado.getFecha();
            if (fechaBD != null && fechaBD.length() == 8) {
                jFormattedTextFieldDFecha.setText(fechaBD.substring(0, 4) + "/" 
                                                + fechaBD.substring(4, 6) + "/" 
                                                + fechaBD.substring(6, 8));
            }

            try {
                int hIni = Integer.parseInt(servicioSeleccionado.getHoraInicio().substring(0, 2));
                int mIni = Integer.parseInt(servicioSeleccionado.getHoraInicio().substring(2, 4));
                int hFin = Integer.parseInt(servicioSeleccionado.getHoraFin().substring(0, 2));
                int mFin = Integer.parseInt(servicioSeleccionado.getHoraFin().substring(2, 4));

                jSpinnerHoraIni.setValue(hIni);
                jSpinnerMinInicio.setValue(mIni);
                jSpinnerHoraFin.setValue(hFin);
                jSpinnerMinFin.setValue(mFin);
            } catch (NumberFormatException ex) {
                 JOptionPane.showMessageDialog(this, "Error al leer formato de hora de BD.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private boolean validarHora(int minTotalIni, int minTotalFin) {
        if (minTotalFin <= minTotalIni) {
            JOptionPane.showMessageDialog(this,
                    "La hora de fin debe ser posterior a la hora de inicio.",
                    "Error de Datos",
                    JOptionPane.ERROR_MESSAGE);

            return false;
        }
        return true;
    }

    private void cargarTabla() {
        DefaultTableModel tablaModel = (DefaultTableModel) jTableServicios.getModel();
        tablaModel.setRowCount(0);

        try {
            String nifActual = FMenuPrincipal.usuario.getNif();
            listaServicios = dmServicios.listarPorTrabajador(nifActual);

            for (DBServicios servicio : listaServicios) {

                String fechaFormateada = servicio.getFecha().substring(0, 4) + "/"
                        + servicio.getFecha().substring(4, 6) + "/"
                        + servicio.getFecha().substring(6, 8);

                String horaIniFormateada = servicio.getHoraInicio().substring(0, 2) + ":"
                        + servicio.getHoraInicio().substring(2, 4);

                String horaFinFormateada = servicio.getHoraFin().substring(0, 2) + ":"
                        + servicio.getHoraFin().substring(2, 4);

                String descripcionObra = servicio.getCodObra();
                for (DBObras obra : listaObras) {
                    if (obra.getCodObra().equals(servicio.getCodObra())) {
                        descripcionObra = obra.getDescripcion();
                        break;
                    }
                }

                tablaModel.addRow(new Object[]{
                    descripcionObra, fechaFormateada, horaIniFormateada, horaFinFormateada
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los serviicos", "ERROR", JOptionPane.ERROR);
        }

        tablaModel.setNumRows(listaObras.size());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenuServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenuServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenuServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenuServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenuServicios().setVisible(true);
            }
        });
    }
    
    private void cargarObras() {
        try {
            DMObras query = new DMObras();
            listaObras = query.obtenerTodasObras();

            jcbObras.removeAllItems();
            for (DBObras o : listaObras) {
                jcbObras.addItem(o.getDescripcion());
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al cargar trabajadores: " + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldDFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerHoraFin;
    private javax.swing.JSpinner jSpinnerHoraIni;
    private javax.swing.JSpinner jSpinnerMinFin;
    private javax.swing.JSpinner jSpinnerMinInicio;
    private javax.swing.JTable jTableServicios;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbInsertar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JComboBox<String> jcbObras;
    private javax.swing.JLabel jlErrorHoraFin;
    private javax.swing.JLabel jlTrabajador;
    // End of variables declaration//GEN-END:variables

}
