package Formularios;

import DBConexiones.ConexionDB;
import static Formularios.FAutenticar.loginCorrecto;
import MapeoTablas.DBTrabajadores;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import java.net.URL;

/**
 *
 * @author miare
 */
public class FMenuPrincipal extends javax.swing.JFrame {

    public static DBTrabajadores usuario;

    private HelpSet hs;
    private HelpBroker hb;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FMenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public FMenuPrincipal() {
        initComponents();
        cargarAyuda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOperaciones = new javax.swing.JMenu();
        jMenuMantenimiento = new javax.swing.JMenu();
        jMenuItemObras = new javax.swing.JMenuItem();
        jMenuItemTrabajadores = new javax.swing.JMenuItem();
        jMenuItemServicios = new javax.swing.JMenuItem();
        jMenuInformes = new javax.swing.JMenu();
        jMenuItemListadoTrabajadores = new javax.swing.JMenuItem();
        jMenuItemListadoObras = new javax.swing.JMenuItem();
        jMenuItemTrabajadorPorObra = new javax.swing.JMenuItem();
        jMenuItemObrasPorTrabajador = new javax.swing.JMenuItem();
        jMenuItemTrabajadorPorObraParam = new javax.swing.JMenuItem();
        jMenuItemObrasPorTrabajadorParam = new javax.swing.JMenuItem();
        jMenuItemRanking = new javax.swing.JMenuItem();
        jMenuAutenticar = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel2.setText("PRUEBA APLICACION");

        jMenuOperaciones.setText("Operaciones");

        jMenuMantenimiento.setText("Mantenimiento");
        jMenuMantenimiento.setEnabled(false);

        jMenuItemObras.setText("Obras");
        jMenuItemObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemObrasActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemObras);

        jMenuItemTrabajadores.setText("Trabajadores");
        jMenuItemTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrabajadoresActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemTrabajadores);

        jMenuOperaciones.add(jMenuMantenimiento);

        jMenuItemServicios.setText("Servicios");
        jMenuItemServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServiciosActionPerformed(evt);
            }
        });
        jMenuOperaciones.add(jMenuItemServicios);

        jMenuBar1.add(jMenuOperaciones);

        jMenuInformes.setText("Informes");

        jMenuItemListadoTrabajadores.setText("Listado Trabajadores");
        jMenuItemListadoTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoTrabajadoresActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemListadoTrabajadores);

        jMenuItemListadoObras.setText("Listado Obras");
        jMenuItemListadoObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoObrasActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemListadoObras);

        jMenuItemTrabajadorPorObra.setText("Listado Trabajadores por Obra");
        jMenuItemTrabajadorPorObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrabajadorPorObraActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemTrabajadorPorObra);

        jMenuItemObrasPorTrabajador.setText("Listado Obras por Trabajador");
        jMenuItemObrasPorTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemObrasPorTrabajadorActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemObrasPorTrabajador);

        jMenuItemTrabajadorPorObraParam.setText("Listado Trabajadores por Obra Parametros");
        jMenuItemTrabajadorPorObraParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrabajadorPorObraParamActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemTrabajadorPorObraParam);

        jMenuItemObrasPorTrabajadorParam.setText("Listado Obras por Trabajador Parametros");
        jMenuItemObrasPorTrabajadorParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemObrasPorTrabajadorParamActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemObrasPorTrabajadorParam);

        jMenuItemRanking.setText("Ranking Trabajadores");
        jMenuItemRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRankingActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemRanking);

        jMenuBar1.add(jMenuInformes);

        jMenuAutenticar.setText("Autenticar");

        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenuAutenticar.add(jMenuItemLogin);
        jMenuAutenticar.add(jSeparator1);

        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.setEnabled(false);
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenuAutenticar.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenuAutenticar);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAyuda.setText("Contenido de ayuda");
        jMenuItemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAyudaActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAyuda);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        // TODO add your handling code here:
        FAutenticar login = new FAutenticar();
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoginActionPerformed


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        //0 == mantenimiento / 1 == servicios
        if (loginCorrecto) {
            jMenuItemLogin.setEnabled(false);
            jMenuItemCerrarSesion.setEnabled(true);
            jMenuOperaciones.setEnabled(true);
            jLabelUsuario.setText(usuario.getDescripcion());

            switch (usuario.getTipo()) {
                case 0:
                    jMenuMantenimiento.setEnabled(true);
                    break;
                case 1:
                    jMenuItemServicios.setEnabled(true);
                    break;
                default:
                    throw new AssertionError();
            }
        } else {
            jMenuItemLogin.setEnabled(true);
            jMenuItemCerrarSesion.setEnabled(false);
            jMenuItemServicios.setEnabled(false);
            jMenuMantenimiento.setEnabled(false);
            jMenuOperaciones.setEnabled(false);

            usuario = null;
            jLabelUsuario.setText("");

        }
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        // TODO add your handling code here:
        loginCorrecto = false;
        JOptionPane.showMessageDialog(this, "Has cerrado sesion correctamente", "Cerrando sesion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTrabajadoresActionPerformed
        // TODO add your handling code here:
        FMntoTrabajadores viewMntoTrabajadores = new FMntoTrabajadores();
        viewMntoTrabajadores.setVisible(true);
    }//GEN-LAST:event_jMenuItemTrabajadoresActionPerformed

    private void jMenuItemObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemObrasActionPerformed
        // TODO add your handling code here:
        FMntoObras viewMntoObras = new FMntoObras();
        viewMntoObras.setVisible(true);
    }//GEN-LAST:event_jMenuItemObrasActionPerformed

    private void jMenuItemServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServiciosActionPerformed
        // TODO add your handling code here:
        FMenuServicios viewServicios = new FMenuServicios();
        viewServicios.setVisible(true);
    }//GEN-LAST:event_jMenuItemServiciosActionPerformed

    private void jMenuItemListadoTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoTrabajadoresActionPerformed
        // TODO add your handling code here:
        mostrarInformeObras("ListadoTrabajadores.jasper");
    }//GEN-LAST:event_jMenuItemListadoTrabajadoresActionPerformed

    private void jMenuItemListadoObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoObrasActionPerformed
        // TODO add your handling code here:
        mostrarInformeObras("ListadoObras.jasper");
    }//GEN-LAST:event_jMenuItemListadoObrasActionPerformed

    private void jMenuItemTrabajadorPorObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTrabajadorPorObraActionPerformed
        // TODO add your handling code here:
        mostrarInformeObras("ListadoTrabajadoresPorObra.jasper");
    }//GEN-LAST:event_jMenuItemTrabajadorPorObraActionPerformed

    private void jMenuItemObrasPorTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemObrasPorTrabajadorActionPerformed
        // TODO add your handling code here:
        mostrarInformeObras("ListadoObrasPorCadaTrabajador.jasper");
    }//GEN-LAST:event_jMenuItemObrasPorTrabajadorActionPerformed

    private void jMenuItemTrabajadorPorObraParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTrabajadorPorObraParamActionPerformed
        // TODO add your handling code here:
        mostrarInformeObras("ListadoTrabajadoresPorObraParametros.jasper");
    }//GEN-LAST:event_jMenuItemTrabajadorPorObraParamActionPerformed

    private void jMenuItemObrasPorTrabajadorParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemObrasPorTrabajadorParamActionPerformed
        // TODO add your handling code here:
        mostrarInformeObras("ListadoObrasPorCadaTrabajadorParametros.jasper");
    }//GEN-LAST:event_jMenuItemObrasPorTrabajadorParamActionPerformed

    private void jMenuItemRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRankingActionPerformed
        // TODO add your handling code here:
        mostrarInformeObras("RankingTrabajadores.jasper");
    }//GEN-LAST:event_jMenuItemRankingActionPerformed

    private void jMenuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAyudaActionPerformed
        // TODO add your handling code here:
        if (hb != null && hs != null) {
            try {
                new javax.help.CSH.DisplayHelpFromSource(hb).actionPerformed(evt);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "El sistema de ayuda no está cargado.");
        }
    }//GEN-LAST:event_jMenuItemAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FMenuPrincipal().setVisible(true));
    }

    public void mostrarInformes(String nombreArchivoJasper, HashMap<String, Object> parametros) {
        Connection conexion = null;
        ConexionDB db = null;
        InputStream informeStream = null;

        try {
            db = new ConexionDB();
            conexion = db.conex;

            if (conexion == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo establecer la conexión a la base de datos.",
                        "Error de Conexión",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            String rutaJasper = "informes/" + nombreArchivoJasper;
            informeStream = getClass().getClassLoader().getResourceAsStream(rutaJasper);

            if (informeStream == null) {
                JOptionPane.showMessageDialog(this,
                        "Error: No se pudo encontrar el archivo .jasper en el classpath: " + rutaJasper,
                        "Error de Archivo",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            JasperPrint reporteLleno = JasperFillManager.fillReport(informeStream, parametros, conexion);

            if (reporteLleno.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "El informe no contiene datos para mostrar. (Verifique el rango de fechas introducido).",
                        "Sin Resultados",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JasperViewer viewer = new JasperViewer(reporteLleno, false);
                viewer.setTitle("Informe - " + nombreArchivoJasper.replace(".jasper", ""));
                viewer.setVisible(true);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this, "Error de conexión SQL/BD: " + e.getMessage(),
                    "Error SQL",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al generar o mostrar el informe. Verifique la ruta y la compilación del .jasper.",
                    "Error Informe",
                    JOptionPane.ERROR_MESSAGE);

            e.printStackTrace();
        } finally {
            try {
                if (informeStream != null) {
                    informeStream.close();
                }
            } catch (java.io.IOException e) {
            }
            if (db != null) {
                db.closeConnection();
            }
        }
    }

    public void mostrarInformeObras(String nombreArchivoJasper) {
        InputStream imagenStream = getClass().getClassLoader().getResourceAsStream("imagenes/rolex.png");
        HashMap<String, Object> parametros = new HashMap<>();
        parametros.put("_IMG_ROLEX", imagenStream);

        if (nombreArchivoJasper.contains("Parametros")) {

            String fechaInicioStr = JOptionPane.showInputDialog(
                    this, "Introduce la Fecha de Inicio (YYYY-MM-DD):", "Filtro de Fechas", JOptionPane.QUESTION_MESSAGE
            );

            if (fechaInicioStr == null || fechaInicioStr.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Operación cancelada. Debe introducir la fecha de inicio.", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            String fechaFinStr = JOptionPane.showInputDialog(
                    this, "Introduce la Fecha de Fin (YYYY-MM-DD):", "Filtro de Fechas", JOptionPane.QUESTION_MESSAGE
            );

            if (fechaFinStr == null || fechaFinStr.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Operación cancelada. Debe introducir la fecha de fin.", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            parametros.put("FechaInicio", fechaInicioStr.trim());
            parametros.put("FechaFin", fechaFinStr.trim());
        }

        mostrarInformes(nombreArchivoJasper, parametros);
    }

    public void cargarAyuda() {
        try {
            URL hsURL = getClass().getResource("/ayuda/helpset.hs");

            if (hsURL == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "No se encuentra el archivo helpset.hs\nComprueba la ruta /ayuda/helpset.hs",
                        "Error JavaHelp",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            hs = new HelpSet(null, hsURL);
            hb = hs.createHelpBroker();

            // Botón de ayuda
            hb.enableHelpOnButton(jMenuItemAyuda, "introduccion", hs);

            // Tecla F1
            hb.enableHelpKey(this.getContentPane(), "introduccion", hs);

            System.out.println("JavaHelp cargado correctamente.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error cargando el sistema de ayuda:\n" + e.getMessage(),
                    "Error JavaHelp",
                    JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenuAutenticar;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInformes;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemListadoObras;
    private javax.swing.JMenuItem jMenuItemListadoTrabajadores;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemObras;
    private javax.swing.JMenuItem jMenuItemObrasPorTrabajador;
    private javax.swing.JMenuItem jMenuItemObrasPorTrabajadorParam;
    private javax.swing.JMenuItem jMenuItemRanking;
    private javax.swing.JMenuItem jMenuItemServicios;
    private javax.swing.JMenuItem jMenuItemTrabajadorPorObra;
    private javax.swing.JMenuItem jMenuItemTrabajadorPorObraParam;
    private javax.swing.JMenuItem jMenuItemTrabajadores;
    private javax.swing.JMenu jMenuMantenimiento;
    private javax.swing.JMenu jMenuOperaciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
