/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import DModules.DMTrabajadores;
import MapeoTablas.DBTrabajadores;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author miare
 */
public class FMntoTrabajadores extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FMntoTrabajadores.class.getName());
    ArrayList<DBTrabajadores> listaTrabajadores = new ArrayList<>();

    private DefaultTableModel modelTrabla;

    /**
     * Creates new form JMntoTrabajadores
     */
    public FMntoTrabajadores() {
        initComponents();
        modelTrabla = (DefaultTableModel) this.jTableTrabajadores.getModel();
    }

    public void cargarTrabla() {
        try {
            DMTrabajadores cargarTrabajadores = new DMTrabajadores();
            listaTrabajadores = cargarTrabajadores.jcbCargaComboTrabajadores();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los trabajadores", "ERROR", JOptionPane.ERROR);
        }

        modelTrabla.setRowCount(0);
        modelTrabla.setNumRows(listaTrabajadores.size());

        for (int fila = 0; fila < modelTrabla.getRowCount(); fila++) {
            DBTrabajadores trabajador = listaTrabajadores.get(fila);

            String tipo = "";
            if (trabajador.getTipo() == 0) {
                tipo = "Administrativo";
            } else {
                tipo = "Servicios";
            }

            modelTrabla.setValueAt(listaTrabajadores.get(fila).getNif(), fila, 0);
            modelTrabla.setValueAt(listaTrabajadores.get(fila).getNombre(), fila, 1);
            modelTrabla.setValueAt(listaTrabajadores.get(fila).getPoblacion(), fila, 2);
            modelTrabla.setValueAt(tipo, fila, 3);
            modelTrabla.setValueAt(listaTrabajadores.get(fila).getPvpHora(), fila, 4);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTrabajadores = new javax.swing.JTable();
        jButtonCancelar = new javax.swing.JButton();
        jPanelInsertar1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombreTrabajador = new javax.swing.JTextField();
        jComboBoxMnto1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldDocumentacion = new javax.swing.JFormattedTextField();
        jLabelPvpHora1 = new javax.swing.JLabel();
        jTextFieldPoblacion = new javax.swing.JTextField();
        jRadioButtonAdministracion = new javax.swing.JRadioButton();
        jRadioButtonServicios = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerPvpHora = new javax.swing.JSpinner();
        jButtonInsertTrabajadores = new javax.swing.JButton();
        jButtonEliminarTrabajadores = new javax.swing.JButton();
        jButtonModificarTrabajadores = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU MANTENIMIENTO DE TRABAJADORES");

        jTableTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIF", "NOMBRE", "POBLACION", "TIPO", "PVP_HORA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTrabajadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTrabajadores);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jPanelInsertar1.setToolTipText("");

        jLabel5.setText("Nombre del trabajador");

        jComboBoxMnto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIF", "NIE", "CIF", "Libre" }));
        jComboBoxMnto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMnto1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo:");

        jFormattedTextFieldDocumentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDocumentacionActionPerformed(evt);
            }
        });

        jLabelPvpHora1.setText("PVP Hora");

        buttonGroup2.add(jRadioButtonAdministracion);
        jRadioButtonAdministracion.setText("Administracion");

        buttonGroup2.add(jRadioButtonServicios);
        jRadioButtonServicios.setText("Servicios");

        jLabel7.setText("Poblacion");

        jSpinnerPvpHora.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        javax.swing.GroupLayout jPanelInsertar1Layout = new javax.swing.GroupLayout(jPanelInsertar1);
        jPanelInsertar1.setLayout(jPanelInsertar1Layout);
        jPanelInsertar1Layout.setHorizontalGroup(
            jPanelInsertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertar1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelInsertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMnto1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInsertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addComponent(jLabelPvpHora1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelInsertar1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonAdministracion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFormattedTextFieldDocumentacion)
                    .addComponent(jTextFieldNombreTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(jTextFieldPoblacion)
                    .addComponent(jSpinnerPvpHora))
                .addGap(0, 66, Short.MAX_VALUE))
        );
        jPanelInsertar1Layout.setVerticalGroup(
            jPanelInsertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertar1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelInsertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMnto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButtonAdministracion)
                    .addComponent(jRadioButtonServicios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInsertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPvpHora1)
                    .addComponent(jSpinnerPvpHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jButtonInsertTrabajadores.setText("Insertar");
        jButtonInsertTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertTrabajadoresActionPerformed(evt);
            }
        });

        jButtonEliminarTrabajadores.setText("Eliminar");
        jButtonEliminarTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarTrabajadoresActionPerformed(evt);
            }
        });

        jButtonModificarTrabajadores.setText("Modificar");
        jButtonModificarTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarTrabajadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jPanelInsertar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonInsertTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButtonEliminarTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButtonModificarTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInsertar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonInsertTrabajadores)
                    .addComponent(jButtonEliminarTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonModificarTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        MaskFormatter formatter;
        try {
            formatter = new MaskFormatter("########U");
            formatter.setPlaceholderCharacter('_');

            jFormattedTextFieldDocumentacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatter));
            jFormattedTextFieldDocumentacion.setValue(null);

        } catch (ParseException e) {
            System.out.println("ERROR: " + e.getMessage());
        }
        cargarTrabla();
        jButtonCancelar.setVisible(false);
        jButtonEliminarTrabajadores.setVisible(false);
        jButtonModificarTrabajadores.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jButtonInsertTrabajadores.setVisible(true);
        jButtonEliminarTrabajadores.setVisible(false);
        jButtonModificarTrabajadores.setVisible(false);
        jButtonCancelar.setVisible(false);

        jTextFieldNombreTrabajador.setText("");
        jFormattedTextFieldDocumentacion.setValue(null);
        buttonGroup2.clearSelection();
        jTextFieldPoblacion.setText("");
        jSpinnerPvpHora.setValue(0);
        jFormattedTextFieldDocumentacion.setEditable(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void establecerTipoDocumentacion(String nif) {
        String tipoDocumento = "NIF";

        String nifLimpio = nif.replace("_", "").trim();

        if (nifLimpio.length() >= 1) {
            char primerCaracter = nifLimpio.toUpperCase().charAt(0);

            if (primerCaracter == 'X' || primerCaracter == 'Y' || primerCaracter == 'Z') {
                tipoDocumento = "NIE";
            } else if (Character.isLetter(primerCaracter)) {
                tipoDocumento = "CIF";
            } else if (nifLimpio.length() < 9) {

            }

        }

        jComboBoxMnto1.setSelectedItem(tipoDocumento);

        MaskFormatter formatter;
        formatter = null;
        try {
            switch (tipoDocumento) {
                case "NIF":
                    formatter = new MaskFormatter("########U");
                    formatter.setPlaceholderCharacter('_');
                    break;
                case "CIF":
                    formatter = new MaskFormatter("U########");
                    formatter.setPlaceholderCharacter('_');
                    break;
                case "NIE":
                    formatter = new MaskFormatter("U#######U");
                    formatter.setPlaceholderCharacter('_');
                    break;
                case "Libre":
                    formatter = new MaskFormatter("*********");
                    formatter.setPlaceholderCharacter('_');
                    break;
            }

            jFormattedTextFieldDocumentacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatter));
            jFormattedTextFieldDocumentacion.setText(nif);
        } catch (ParseException ex) {
            System.err.println("Error al aplicar máscara: " + ex.getMessage());
        }
    }

    private void setCamposFromTable() {
        int filaSeleccionada = jTableTrabajadores.getSelectedRow();

        if (filaSeleccionada >= 0) {
            DBTrabajadores trabajador = listaTrabajadores.get(filaSeleccionada);

            establecerTipoDocumentacion(trabajador.getNif());

            jTextFieldNombreTrabajador.setText(trabajador.getNombre());
            jTextFieldPoblacion.setText(trabajador.getPoblacion());
            jSpinnerPvpHora.setValue(trabajador.getPvpHora());

            int tipo = trabajador.getTipo();

            if (tipo == 0) {
                jRadioButtonAdministracion.setSelected(true);
                jRadioButtonServicios.setSelected(false);
            } else if (tipo == 1) {
                jRadioButtonServicios.setSelected(true);
                jRadioButtonAdministracion.setSelected(false);

            } else {
                buttonGroup2.clearSelection();
            }
        }
    }

    private void jButtonModificarTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarTrabajadoresActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNombreTrabajador.getText();
        String dni = jFormattedTextFieldDocumentacion.getText();
        int tipo;

        if (jRadioButtonAdministracion.isSelected()) {
            tipo = 0;
        } else if (jRadioButtonServicios.isSelected()) {
            tipo = 1;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Tipo de trabajador.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int pvpHora = (int) jSpinnerPvpHora.getValue();
        String poblacion = jTextFieldPoblacion.getText();

        if (nombre.isEmpty() || dni.isEmpty() || dni.contains("_") || poblacion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos obligatorios deben estar llenos y el NIF completo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DBTrabajadores trabajadorModificar = new DBTrabajadores(dni, nombre, poblacion, null, tipo, pvpHora);

        try {
            DMTrabajadores query = new DMTrabajadores();
            System.out.println("haciendo la query");
            query.modificarTrabajador(trabajadorModificar);
            System.out.println("Qeury hecha");
            JOptionPane.showMessageDialog(this, "Trabajador modificado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            limpiarCampos();
            cargarTrabla();

            jButtonCancelarActionPerformed(evt);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos al modificar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModificarTrabajadoresActionPerformed

    private void jButtonInsertTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertTrabajadoresActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNombreTrabajador.getText();
        String dni = jFormattedTextFieldDocumentacion.getText();
        int tipo;
        if (jRadioButtonAdministracion.isSelected()) {
            tipo = 0;
        } else if (jRadioButtonServicios.isSelected()) {
            tipo = 1;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Tipo de trabajador.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int pvpHora = (int) jSpinnerPvpHora.getValue();
        String poblacion = jTextFieldPoblacion.getText();

        if (nombre.isEmpty() || dni.isEmpty() || poblacion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DBTrabajadores nuevoTrabajador = new DBTrabajadores(dni, nombre, poblacion, null, tipo, pvpHora);

        try {
            DMTrabajadores query = new DMTrabajadores();
            query.insertarTrabajador(nuevoTrabajador);

            JOptionPane.showMessageDialog(this, "Trabajador insertado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            limpiarCampos();
            cargarTrabla();
        } catch (SQLException e) {
            System.err.println("Error al insertar trabajador: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonInsertTrabajadoresActionPerformed

    private void jButtonEliminarTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTrabajadoresActionPerformed
        // TODO add your handling code here:
        String nifAEliminar = jFormattedTextFieldDocumentacion.getText().replace("_", "").trim();

        if (nifAEliminar.isEmpty() || nifAEliminar.length() < 8) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un trabajador (NIF/CIF/NIE incompleto).", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "Estas seguro de eliminar permanentemente al trabajador",
                "Confirmar Eliminacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                DMTrabajadores query = new DMTrabajadores();
                boolean eliminado = query.eliminarTrabajadores(nifAEliminar);

                if (eliminado) {
                    JOptionPane.showMessageDialog(this,
                            "Trabajador eliminado con éxito.",
                            "Eliminación Correcta",
                            JOptionPane.INFORMATION_MESSAGE);

                    limpiarCampos();
                    cargarTrabla();
                    jButtonCancelarActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "No se pudo eliminar el trabajador: tiene servicios asociados o no existe.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,
                        "Error de Base de Datos al eliminar: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonEliminarTrabajadoresActionPerformed

    private void jTableTrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTrabajadoresMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            jButtonInsertTrabajadores.setVisible(false);
            jButtonEliminarTrabajadores.setVisible(true);
            jButtonModificarTrabajadores.setVisible(true);
            jButtonCancelar.setVisible(true);
            jFormattedTextFieldDocumentacion.setEditable(false);

            setCamposFromTable();

        }
    }//GEN-LAST:event_jTableTrabajadoresMouseClicked

    private void jFormattedTextFieldDocumentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDocumentacionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jFormattedTextFieldDocumentacionActionPerformed

    private void jComboBoxMnto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMnto1ActionPerformed
        // TODO add your handling code here:
        String seleccion = (String) jComboBoxMnto1.getSelectedItem();
        MaskFormatter formatter;
        formatter = null;
        try {
            switch (seleccion) {
                case "NIF":
                    formatter = new MaskFormatter("########U");
                    formatter.setPlaceholderCharacter('_');
                    break;
                case "CIF":
                    formatter = new MaskFormatter("U########");
                    formatter.setPlaceholderCharacter('_');
                    break;
                case "NIE":
                    formatter = new MaskFormatter("U#######U");
                    formatter.setPlaceholderCharacter('_');
                    break;
                case "Libre":
                    formatter = new MaskFormatter("*********");
                    formatter.setPlaceholderCharacter('_');
                    break;
            }

            jFormattedTextFieldDocumentacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatter));
            jFormattedTextFieldDocumentacion.setValue(null);
        } catch (ParseException ex) {
            // Esto solo se ejecuta si defines mal una máscara (ej: "###" en vez de "###")

        }
    }//GEN-LAST:event_jComboBoxMnto1ActionPerformed

    private void limpiarCampos() {
        jTextFieldNombreTrabajador.setText("");
        jFormattedTextFieldDocumentacion.setValue(null);
        jTextFieldPoblacion.setText("");
        jSpinnerPvpHora.setValue(0);
        buttonGroup2.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FMntoTrabajadores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminarTrabajadores;
    private javax.swing.JButton jButtonInsertTrabajadores;
    private javax.swing.JButton jButtonModificarTrabajadores;
    private javax.swing.JComboBox<String> jComboBoxMnto1;
    private javax.swing.JFormattedTextField jFormattedTextFieldDocumentacion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelPvpHora1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelInsertar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonAdministracion;
    private javax.swing.JRadioButton jRadioButtonServicios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerPvpHora;
    private javax.swing.JTable jTableTrabajadores;
    private javax.swing.JTextField jTextFieldNombreTrabajador;
    private javax.swing.JTextField jTextFieldPoblacion;
    // End of variables declaration//GEN-END:variables
}
