/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import DModules.DMObras;
import MapeoTablas.DBObras;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author miare
 */
public class FMntoObras extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FMntoObras.class.getName());
    private ArrayList<DBObras> listaObras = new ArrayList<>();

    private DefaultTableModel tablaModel;

    private static final DateTimeFormatter FORMATO_ENTRADA = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private static final DateTimeFormatter FORMATO_SALIDA_BD = DateTimeFormatter.ofPattern("yyyyMMdd");

    /**
     * Creates new form FMntoObras
     */
    public FMntoObras() {
        initComponents();
        tablaModel = (DefaultTableModel) jTableObras.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneObras = new javax.swing.JScrollPane();
        jTableObras = new javax.swing.JTable();
        jLabelCodObra = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDesc = new javax.swing.JLabel();
        jLabelFecFin = new javax.swing.JLabel();
        jTextFieldCodObra = new javax.swing.JTextField();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jButtonInsertar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jFormattedTextFieldFecFin = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableObras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo de Obra", "Descripcion", "Fecha Fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableObras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableObrasMouseClicked(evt);
            }
        });
        jScrollPaneObras.setViewportView(jTableObras);

        jLabelCodObra.setText("CODIGO DE OBRA:");

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU MANTENIMIENTO DE OBRAS");

        jLabelDesc.setText("DESCRIPCION:");

        jLabelFecFin.setText("FECHA DE FINALIZACIÓN:");

        jTextFieldCodObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodObraActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jFormattedTextFieldFecFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldFecFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelFecFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCodObra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCodObra, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jTextFieldDescripcion)
                    .addComponent(jFormattedTextFieldFecFin))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE))
                    .addComponent(jScrollPaneObras))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodObra)
                    .addComponent(jTextFieldCodObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDesc)
                            .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEliminar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFecFin)
                            .addComponent(jFormattedTextFieldFecFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPaneObras, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String procesarFecha(String fechaStr) throws DateTimeParseException {
        String fechaLimpia = fechaStr.replaceAll("[_/ ]", "");

        if (fechaLimpia.isEmpty()) {
            return null;
        }

        try {
            return FORMATO_SALIDA_BD.format(java.time.LocalDate.parse(fechaStr, FORMATO_ENTRADA));
        } catch (DateTimeParseException e) {
            throw e;
        }
    }

    private void jTextFieldCodObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodObraActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        String codObra = jTextFieldCodObra.getText();
        String descripcion = jTextFieldDescripcion.getText();
        String fechaFinStr = jFormattedTextFieldFecFin.getText();

        if (codObra.isEmpty() || descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos obligatorios deben estar llenos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String fechaFinBD;
        try {
            fechaFinBD = procesarFecha(fechaFinStr);
        } catch (DateTimeParseException e) {
            if (fechaFinStr.contains("_")) {
                fechaFinBD = "21001231";
            } else {
                JOptionPane.showMessageDialog(this,
                        "Formato de fecha de finalización incorrecto. Debe ser dd/MM/yyyy.",
                        "Error de Formato",
                        JOptionPane.ERROR_MESSAGE);
                
                return;
            }
        }

        if (fechaFinBD == null || fechaFinBD.isEmpty()) {
            fechaFinBD = "21001231";
        }

        DBObras obraModificar = new DBObras(codObra, descripcion, fechaFinBD);

        try {
            DMObras query = new DMObras();
            query.modificarObra(obraModificar);

            JOptionPane.showMessageDialog(this, "Obra modificada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            jButtonCancelarActionPerformed(evt);
            cargarTabla();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos al modificar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        MaskFormatter formatter;
        try {
            formatter = new MaskFormatter("##/##/####");
            formatter.setPlaceholderCharacter('_');

            jFormattedTextFieldFecFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatter));
            jFormattedTextFieldFecFin.setValue(null);

        } catch (ParseException e) {
            System.out.println("ERROR: " + e.getMessage());
        }
        cargarTabla();
        jButtonInsertar.setEnabled(true);
        jButtonModificar.setEnabled(false);
        jButtonEliminar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        // TODO add your handling code here:
        String codObra = jTextFieldCodObra.getText();
        String descripcion = jTextFieldDescripcion.getText();
        String fechaFinStr = jFormattedTextFieldFecFin.getText();

        if (codObra.isEmpty() || descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacios", "ERROR!!", JOptionPane.ERROR);
            return;
        }

        String fechaFinBD;
        try {
            fechaFinBD = procesarFecha(fechaFinStr);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha de finalización incorrecto. Debe ser dd/MM/yyyy. Si no tiene fecha, déjelo vacío.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            DMObras query = new DMObras();
            DBObras obra = new DBObras(codObra, descripcion, fechaFinBD);

            if (fechaFinBD == null || fechaFinBD.isEmpty()) {
                query.insertarObraSinFecha(obra);
            } else {
                query.insertarObra(obra);
            }

            JOptionPane.showMessageDialog(this, "Trabajador insertado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            limpiarCampos();
            cargarTabla();
        } catch (SQLException ex) {
            System.err.println("Error al insertar trabajador: " + ex.getMessage());
        }


    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jFormattedTextFieldFecFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFecFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldFecFinActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jButtonInsertar.setEnabled(true);
        jButtonModificar.setEnabled(false);
        jButtonEliminar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jTextFieldCodObra.setEditable(true);

        jTextFieldCodObra.setText("");
        jFormattedTextFieldFecFin.setText("");
        jTextFieldDescripcion.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableObrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableObrasMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            jButtonInsertar.setEnabled(false);
            jButtonModificar.setEnabled(true);
            jButtonEliminar.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            jTextFieldCodObra.setEnabled(false);

            setCamposFromTable();
        }
    }//GEN-LAST:event_jTableObrasMouseClicked

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        String codObra = jTextFieldCodObra.getText();

        if (codObra.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Obra de la tabla para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar la obra con código?",
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                DMObras query = new DMObras();

                boolean eliminado = query.eliminarObra(codObra);

                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Obra eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                    jButtonCancelarActionPerformed(evt);
                    cargarTabla();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "No se puede eliminar la obra porque tiene servicios asociados. Elimine los servicios primero.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,
                        "Error de base de datos al eliminar: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void setCamposFromTable() {
        int filaSeleccionada = jTableObras.getSelectedRow();

        if (filaSeleccionada >= 0) {
            DBObras obra = listaObras.get(filaSeleccionada);

            jTextFieldCodObra.setText(obra.getCodObra());
            jTextFieldDescripcion.setText(obra.getDescripcion());

            String fechaFinBD = obra.getFechaFin();

            if (fechaFinBD != null && !fechaFinBD.isEmpty()) {
                try {
                    LocalDate fecha = LocalDate.parse(fechaFinBD, FORMATO_SALIDA_BD);

                    String fechaFinDisplay = FORMATO_ENTRADA.format(fecha);

                    jFormattedTextFieldFecFin.setText(fechaFinDisplay);
                } catch (DateTimeParseException e) {
                    jFormattedTextFieldFecFin.setText("");
                }
            } else {
                jFormattedTextFieldFecFin.setText("");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FMntoObras().setVisible(true));
    }

    private void cargarTabla() {
        try {
            DMObras cargarObras = new DMObras();
            listaObras = cargarObras.obtenerTodasObras();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los trabajadores", "ERROR", JOptionPane.ERROR);
        }

        tablaModel.setNumRows(listaObras.size());

        for (int fila = 0; fila < tablaModel.getRowCount(); fila++) {
            tablaModel.setValueAt(listaObras.get(fila).getCodObra(), fila, 0);
            tablaModel.setValueAt(listaObras.get(fila).getDescripcion(), fila, 1);
            tablaModel.setValueAt(listaObras.get(fila).getFechaFin(), fila, 2);
        }
    }

    private void limpiarCampos() {
        jTextFieldCodObra.setText("");
        jTextFieldDescripcion.setText("");
        jFormattedTextFieldFecFin.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JFormattedTextField jFormattedTextFieldFecFin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCodObra;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelFecFin;
    private javax.swing.JScrollPane jScrollPaneObras;
    private javax.swing.JTable jTableObras;
    private javax.swing.JTextField jTextFieldCodObra;
    private javax.swing.JTextField jTextFieldDescripcion;
    // End of variables declaration//GEN-END:variables
}
